### PR TITLE
New tranlatetiles right

### LINKED ISSUE #42: Different right for tile translators
There should be two distinct rights: tiletranslator, and whatever the current one is. tiletranslator will allow you to use the TileTranslator and see the "Translate" button on the TileList, while not allowing you to modify tile data or sheet data.

### PR DESCRIPTION
**Pull request by elifoster**
This right was discussed on the SN. This closes #42.

@Alexia @retep998 @xbony2 ?

### CODE REVIEW

**Comment by xbony2** [comment]
It was discussed on the Centralized discussion actually, not the Staff's Noticeboard.

**Comment by Alexia** [comment]
This looks good to me.

**Comment by elifoster** [comment]
@retep998 Thoughts?

**Comment by retep998** [comment]
@elifoster Just make sure that someone from Gamepedia gives out the `translatetiles` right to the appropriate groups.

**Pull request merged**
